#
# Voltus Scheduler command file generated by voltus_rail on Thu Nov 20 16:23:42 2025
#
setvar log_file ./work/voltus_extractor_VDD.log 
setvar output_cache_directory_name /tmp/innovus_temp_24931_ra01_shadab_wNNusj/zx_tmp_ra01_27340
setvar library_name ./run1/era_work/incremental_output0/pgv/techonly.cl
setvar output_directory_name ./work
setvar output_file_name VDD 
setvar max_error_messages 100
setvar max_resistor_length 800
setvar hierarchy_char /
layout_file /tmp/innovus_temp_24931_ra01_shadab_wNNusj/eps_out_24931.def.gz
setvar exec_token "/tmp/innovus_temp_24931_ra01_shadab_wNNusj/eps_out_24931.def.gz"
setvar enable_signal_via_overhang false
setvar zx_multinet_extraction false
setvar extraction_mode early
setvar enable_zx_report_shorts true
extraction_type all none
extraction_type pattern {VDD} r_only 
hierarchical_path_tracer netinst_table ./work/VDD.netinst 
hierarchical_path_tracer cell_table ./work/VDD.cellinst 
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
label port VDDvsrc1 451.5900 221.3600 Metal1
label port VDDvsrc2 451.5900 221.3600 Metal2
label port VDDvsrc3 451.5900 230.8120 Metal3
label port VDDvsrc4 451.5900 230.8120 Metal4
label port VDDvsrc5 451.5900 230.8120 Metal5
label port VDDvsrc6 451.5900 232.9050 Metal6
label port VDDvsrc7 1402.6000 381.0200 Metal1
label port VDDvsrc8 1402.6000 381.0200 Metal2
label port VDDvsrc9 1393.1480 381.0200 Metal3
label port VDDvsrc10 1393.1480 381.0200 Metal4
label port VDDvsrc11 1391.0550 381.0200 Metal5
label port VDDvsrc12 1393.1480 381.0200 Metal6
label port VDDvsrc13 1160.0850 1170.7600 Metal1
label port VDDvsrc14 1160.0850 1170.7600 Metal2
label port VDDvsrc15 1160.0850 1161.3080 Metal3
label port VDDvsrc16 1160.0850 1161.3080 Metal4
label port VDDvsrc17 1160.0850 1161.3080 Metal5
label port VDDvsrc18 1160.0850 1159.2150 Metal6
label port VDDvsrc19 221.3600 971.7150 Metal1
label port VDDvsrc20 221.3600 971.7150 Metal2
label port VDDvsrc21 230.8120 971.7150 Metal3
label port VDDvsrc22 230.8120 971.7150 Metal4
label port VDDvsrc23 232.9050 971.7150 Metal5
label port VDDvsrc24 230.8120 971.7150 Metal6
label port VDDvsrc25 221.3600 861.4500 Metal1
label port VDDvsrc26 221.3600 861.4500 Metal2
label port VDDvsrc27 230.8120 861.4500 Metal3
label port VDDvsrc28 230.8120 861.4500 Metal4
label port VDDvsrc29 232.9050 861.4500 Metal5
label port VDDvsrc30 230.8120 861.4500 Metal6
hierarchical_path_tracer pgnet_table ./work/all.pgnets
setvar output_def false
setvar cluster_via_size 25
setvar cluster_via1_maximum true
setvar def_merge_supply_shorts false
setvar promote_ports true
setvar max_cpu 1
setvar tech_file ../QRC/t018s6mm.tch
setvar density_check_method database
setvar sfedb_path ./work/SFEDB
setvar enable_binary_inst_pgdb true
setvar keep_log_file false
