set_clock_latency -source -early -min -rise  -0.164924 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -early -min -fall  -0.17094 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -late -min -rise  -0.164924 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -late -min -fall  -0.17094 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_156/Y}] -clock vclk2 
set_clock_latency -source -early -min -rise  -0.164924 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -early -min -fall  -0.17094 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -late -min -rise  -0.164924 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -late -min -fall  -0.17094 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_154/Y}] -clock vclk2 
set_clock_latency -source -early -min -rise  -0.164924 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -early -min -fall  -0.17094 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -late -min -rise  -0.164924 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -late -min -fall  -0.17094 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_152/Y}] -clock vclk2 
set_clock_latency -source -early -min -rise  1.7703 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -early -min -fall  1.76346 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -late -min -rise  1.7703 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -late -min -fall  1.76346 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_150/Y}] -clock vclk1 
set_clock_latency -source -early -min -rise  -0.164924 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -early -min -fall  -0.17094 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -late -min -rise  -0.164924 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -late -min -fall  -0.17094 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_160/Y}] -clock vclk2 
set_clock_latency -source -early -min -rise  -0.164924 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
set_clock_latency -source -early -min -fall  -0.17094 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
set_clock_latency -source -late -min -rise  -0.164924 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
set_clock_latency -source -late -min -fall  -0.17094 [get_pins {DTMF_INST/TEST_CONTROL_INST/i_158/Y}] -clock vclk2 
