###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ra01)
#  Generated on:      Fri Nov 21 14:31:38 2025
#  Design:            DTMF_CHIP
#  Command:           create_ccopt_clock_tree_spec -file dtmf_clk.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Timing through the following pins was disabled by case analysis
# These pins are ignore skew pins
set_ccopt_property sink_type -pin DTMF_INST/TDSP_DS_CS_INST/i_4380/B1 ignore
set_ccopt_property sink_type_reasons -pin DTMF_INST/TDSP_DS_CS_INST/i_4380/B1 set_case_analysis
set_ccopt_property sink_type -pin DTMF_INST/TDSP_DS_CS_INST/i_4383/B1 ignore
set_ccopt_property sink_type_reasons -pin DTMF_INST/TDSP_DS_CS_INST/i_4383/B1 set_case_analysis

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin DTMF_INST/TEST_CONTROL_INST/i_150/Y true
set_ccopt_property cts_is_sdc_clock_root -pin DTMF_INST/TEST_CONTROL_INST/i_152/Y true
set_ccopt_property cts_is_sdc_clock_root -pin DTMF_INST/TEST_CONTROL_INST/i_154/Y true
set_ccopt_property cts_is_sdc_clock_root -pin DTMF_INST/TEST_CONTROL_INST/i_156/Y true
set_ccopt_property cts_is_sdc_clock_root -pin DTMF_INST/TEST_CONTROL_INST/i_158/Y true
set_ccopt_property cts_is_sdc_clock_root -pin DTMF_INST/TEST_CONTROL_INST/i_160/Y true

# Clocks present at pin DTMF_INST/TEST_CONTROL_INST/i_152/Y
#   vclk2 (period 14.000ns) in timing_config common([/home/shadab/shadab/FPR/work/preCTSopt.inn.dat/mmmc/modes/common/common.sdc])
create_ccopt_clock_tree -name vclk2 -source DTMF_INST/TEST_CONTROL_INST/i_152/Y -no_skew_group
# Clock period setting for source pin of vclk2
set_ccopt_property clock_period -pin DTMF_INST/TEST_CONTROL_INST/i_152/Y 14

# Clocks present at pin DTMF_INST/TEST_CONTROL_INST/i_154/Y
#   vclk2 (period 14.000ns) in timing_config common([/home/shadab/shadab/FPR/work/preCTSopt.inn.dat/mmmc/modes/common/common.sdc])
create_ccopt_clock_tree -name vclk2<1> -source DTMF_INST/TEST_CONTROL_INST/i_154/Y -no_skew_group
# Clock period setting for source pin of vclk2<1>
set_ccopt_property clock_period -pin DTMF_INST/TEST_CONTROL_INST/i_154/Y 14

# Clocks present at pin DTMF_INST/TEST_CONTROL_INST/i_156/Y
#   vclk2 (period 14.000ns) in timing_config common([/home/shadab/shadab/FPR/work/preCTSopt.inn.dat/mmmc/modes/common/common.sdc])
create_ccopt_clock_tree -name vclk2<2> -source DTMF_INST/TEST_CONTROL_INST/i_156/Y -no_skew_group
# Clock period setting for source pin of vclk2<2>
set_ccopt_property clock_period -pin DTMF_INST/TEST_CONTROL_INST/i_156/Y 14

# Clocks present at pin DTMF_INST/TEST_CONTROL_INST/i_158/Y
#   vclk2 (period 14.000ns) in timing_config common([/home/shadab/shadab/FPR/work/preCTSopt.inn.dat/mmmc/modes/common/common.sdc])
create_ccopt_clock_tree -name vclk2<3> -source DTMF_INST/TEST_CONTROL_INST/i_158/Y -no_skew_group
# Clock period setting for source pin of vclk2<3>
set_ccopt_property clock_period -pin DTMF_INST/TEST_CONTROL_INST/i_158/Y 14

# Clocks present at pin DTMF_INST/TEST_CONTROL_INST/i_160/Y
#   vclk2 (period 14.000ns) in timing_config common([/home/shadab/shadab/FPR/work/preCTSopt.inn.dat/mmmc/modes/common/common.sdc])
create_ccopt_clock_tree -name vclk2<4> -source DTMF_INST/TEST_CONTROL_INST/i_160/Y -no_skew_group
# Clock period setting for source pin of vclk2<4>
set_ccopt_property clock_period -pin DTMF_INST/TEST_CONTROL_INST/i_160/Y 14

# Clocks present at pin DTMF_INST/TEST_CONTROL_INST/i_150/Y
#   vclk1 (period 7.000ns) in timing_config common([/home/shadab/shadab/FPR/work/preCTSopt.inn.dat/mmmc/modes/common/common.sdc])
create_ccopt_clock_tree -name vclk1 -source DTMF_INST/TEST_CONTROL_INST/i_150/Y -no_skew_group
# Clock period setting for source pin of vclk1
set_ccopt_property clock_period -pin DTMF_INST/TEST_CONTROL_INST/i_150/Y 7

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:vclk1 in timing_config:common (sdc /home/shadab/shadab/FPR/work/preCTSopt.inn.dat/mmmc/modes/common/common.sdc)
create_ccopt_skew_group -name vclk1/common -sources DTMF_INST/TEST_CONTROL_INST/i_150/Y -auto_sinks
set_ccopt_property include_source_latency -skew_group vclk1/common true
set_ccopt_property extracted_from_clock_name -skew_group vclk1/common vclk1
set_ccopt_property extracted_from_constraint_mode_name -skew_group vclk1/common common
set_ccopt_property extracted_from_delay_corners -skew_group vclk1/common {dtmf_corner_max dtmf_corner_min}

# Skew group to balance non generated clock:vclk2 in timing_config:common (sdc /home/shadab/shadab/FPR/work/preCTSopt.inn.dat/mmmc/modes/common/common.sdc)
create_ccopt_skew_group -name vclk2/common -sources {DTMF_INST/TEST_CONTROL_INST/i_152/Y DTMF_INST/TEST_CONTROL_INST/i_154/Y DTMF_INST/TEST_CONTROL_INST/i_156/Y DTMF_INST/TEST_CONTROL_INST/i_158/Y DTMF_INST/TEST_CONTROL_INST/i_160/Y} -auto_sinks
set_ccopt_property include_source_latency -skew_group vclk2/common true
set_ccopt_property extracted_from_clock_name -skew_group vclk2/common vclk2
set_ccopt_property extracted_from_constraint_mode_name -skew_group vclk2/common common
set_ccopt_property extracted_from_delay_corners -skew_group vclk2/common {dtmf_corner_max dtmf_corner_min}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

